In [81]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

path = '/Users/macbook/Desktop/projects/Github_Repositories/Trainings/Python_Projects-main/selenium_projects/selenium_06/ebay08_jazz_auto.csv'
df = pd.read_csv(path , usecols= [1,2,3,4,5,6] )
df

,Title,Price,Km,Year,Distance,Description
0,SUCHE Honda Yazz Eleganz Automatik,15.000 € VB,Gesuch 40.000,2016,33607 Mitte (26 km),Barzahler SUCHT Honda Yazz in der Ausstattungs...
1,Honda Jazz 1.4 LS,3.999 €,142.000,2006,59609 Anröchte (27 km),Sonderausstattung: Metallic-Lackierung Weitere...
2,Honda Jazz Elegance 2. HAND NAVI KAMERA SHZ BL...,15.990 €,40.000,2017,33813 Oerlinghausen (27 km),"Herzlich Wilkommen, Wir freuen uns sehr, dass..."
3,Honda Jazz 1.3 i-VTEC Trend CVT*SCHECKHEFT*8-F...,13.380 €,65.718,2017,46117 Oberhausen (112 km),• Fahrer/Beifahrerairbag • Beifahrerairbag abs...
4,Honda Jazz 1.3 Comfort,17.980 €,51.780,2019,30880 Laatzen (110 km),"Honda Jazz: Mit CVT Automatik, Navigation & me..."
5,Auto Honda,4.700 €,80.000,2008,40699 Erkrath (122 km),Reifen 1 Jahre alt Öl Getriebe wurde erneut Da...
6,Honda Jazz 1.4 Comfort| Scheckh.| TÜV NEU| Kli...,3.690 €,181.700,2009,29227 Celle (143 km),TÜV NEU Inspektion NEU Scheckheftgepflegt bei...
7,Honda Jazz 1.4 LS,999 €,95.105,2004,18273 Güstrow (336 km),Sonderausstattung: Metallic-Lackierung Weitere...
8,Honda Jazz Trend i Multif.Lenkrad Klima CD AUX...,7.990 €,143.215,2011,18146 Rostock (358 km),Ausstattungspakete: - Klimaanlage: - Anti-Bloc...
9,"Guten Tag ,das Auto zu verkaufe",3.500 € VB,175.666,2005,12689 Marzahn (360 km),Verkaufe meinen sehr gut erhaltenen Honda Jazz...
10,Honda jazz hybrid Automatik,5.800 € VB,280.000,2012,12687 Marzahn (360 km),Ich verkaufe mein Honda Motor Getriebe lauft s...
11,Honda Jazz 1.4 CVT ES,4.999 €,43.000,2005,89073 Ulm (394 km),Scheckheft gepflegter Garagenwagen (EZ 9/2005)...
12,Honda Jazz 1.2 Trend Klima,2.000 €,183.464,2009,84030 Ergolding (448 km),"Guten Tag, zum Verkauf steht hier ein Honda Ja..."

In [85]:
df['Price'] = df['Price'].str.strip()
df

,Title,Price,Km,Year,Distance,Description
0,SUCHE Honda Yazz Eleganz Automatik,15.000 € VB,Gesuch 40.000,2016,33607 Mitte (26 km),Barzahler SUCHT Honda Yazz in der Ausstattungs...
1,Honda Jazz 1.4 LS,3.999 €,142.000,2006,59609 Anröchte (27 km),Sonderausstattung: Metallic-Lackierung Weitere...
2,Honda Jazz Elegance 2. HAND NAVI KAMERA SHZ BL...,15.990 €,40.000,2017,33813 Oerlinghausen (27 km),"Herzlich Wilkommen, Wir freuen uns sehr, dass..."
3,Honda Jazz 1.3 i-VTEC Trend CVT*SCHECKHEFT*8-F...,13.380 €,65.718,2017,46117 Oberhausen (112 km),• Fahrer/Beifahrerairbag • Beifahrerairbag abs...
4,Honda Jazz 1.3 Comfort,17.980 €,51.780,2019,30880 Laatzen (110 km),"Honda Jazz: Mit CVT Automatik, Navigation & me..."
5,Auto Honda,4.700 €,80.000,2008,40699 Erkrath (122 km),Reifen 1 Jahre alt Öl Getriebe wurde erneut Da...
6,Honda Jazz 1.4 Comfort| Scheckh.| TÜV NEU| Kli...,3.690 €,181.700,2009,29227 Celle (143 km),TÜV NEU Inspektion NEU Scheckheftgepflegt bei...
7,Honda Jazz 1.4 LS,999 €,95.105,2004,18273 Güstrow (336 km),Sonderausstattung: Metallic-Lackierung Weitere...
8,Honda Jazz Trend i Multif.Lenkrad Klima CD AUX...,7.990 €,143.215,2011,18146 Rostock (358 km),Ausstattungspakete: - Klimaanlage: - Anti-Bloc...
9,"Guten Tag ,das Auto zu verkaufe",3.500 € VB,175.666,2005,12689 Marzahn (360 km),Verkaufe meinen sehr gut erhaltenen Honda Jazz...
10,Honda jazz hybrid Automatik,5.800 € VB,280.000,2012,12687 Marzahn (360 km),Ich verkaufe mein Honda Motor Getriebe lauft s...
11,Honda Jazz 1.4 CVT ES,4.999 €,43.000,2005,89073 Ulm (394 km),Scheckheft gepflegter Garagenwagen (EZ 9/2005)...
12,Honda Jazz 1.2 Trend Klima,2.000 €,183.464,2009,84030 Ergolding (448 km),"Guten Tag, zum Verkauf steht hier ein Honda Ja..."

In [72]:
df['Price'] = pd.to_numeric(df['Price'])

In [73]:
df.describe()

           Price          Km         Year
count  11.000000   11.000000    11.000000
mean    4.161636  144.492818  2006.454545
std     1.004829   68.346829     2.910795
min     2.000000   43.000000  2002.000000
25%     3.745000   95.664000  2005.000000
50%     3.999000  161.753000  2006.000000
75%     4.845000  178.683000  2008.500000
max     5.800000  280.000000  2012.000000

In [60]:
df.Km[0] -1

141.0